version: "3"

services:
  shorteneder:
    restart: always
    build: .
    ports:
      - "9000:8080"
    depends_on:
      - app_redis
    env_file:
      - .env
  app_redis:
    image: "redis"
    ports:
      - "6379:6379"
